spring:
  application:
    name: VideoViewsStats
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:video_views_stats;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL; #jdbc:h2:file:/data/demo
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console: #http://localhost:8080/h2-console
      enabled: true
server:
  port: 8080